eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  author: Luiz Delgado
  mail: luiz.delgadov@gmail.com
server:
  port: ${PORT:8888}
message: Mensagem generica
