server:
  port: ${PORT:8080}
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: lb://genre-service
          predicates:
            - Path=/genres/**
